In [7]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np


In [8]:
df=pd.read_csv('customer_churn_dataset.csv')

In [9]:
df.head()

tenure_months  monthly_usage_hours  has_multiple_devices  \
0             39            30.953928                     0   
1             52            20.485203                     0   
2             29            21.684462                     0   
3             15            27.894281                     0   
4             43            19.250190                     1   

   customer_support_calls  payment_failures  is_premium_plan  churn  
0                       1                 0                0      0  
1                       0                 0                0      0  
2                       1                 1                0      0  
3                       1                 0                1      0  
4                       1                 0                0      0

In [10]:
df['churn'].value_counts()

churn
0    48967
1     1033
Name: count, dtype: int64

In [11]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [17]:
X.shape

(50000, 6)

In [19]:
from imblearn.over_sampling import SMOTE
oversample=SMOTE()
X,y=oversample.fit_resample(X,y)

In [20]:
df['churn'].value_counts()

churn
0    48967
1     1033
Name: count, dtype: int64

In [21]:
X.shape

(97934, 6)

In [22]:
y.shape

(97934,)

In [23]:
len(y[y==0])

48967

In [25]:
len(y[y==1])

48967

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,roc_curve
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=15)


In [33]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((73450, 6), (73450,), (24484, 6), (24484,))

In [35]:
X_train

tenure_months  monthly_usage_hours  has_multiple_devices  \
37038             48            20.354947                     1   
1624              54            27.908771                     0   
16631             48            25.296224                     1   
21559             25            28.430001                     0   
26742              5            14.560140                     1   
...              ...                  ...                   ...   
49015             47            27.637737                     0   
68229              5            21.007290                     0   
8076              38            22.740143                     0   
52981             25            20.522640                     0   
7624              53            13.272932                     1   

       customer_support_calls  payment_failures  is_premium_plan  
37038                       1                 0                0  
1624                        3                 0                0  
16631                       5                 0                0  
21559                       0                 0                0  
26742                       0                 0                0  
...                       ...               ...              ...  
49015                       1                 0                0  
68229                       2                 0                0  
8076                        0                 0                0  
52981                       2                 0                0  
7624                        1                 0                0  

[73450 rows x 6 columns]

In [37]:
y_train

37038    0
1624     0
16631    0
21559    0
26742    0
        ..
49015    0
68229    1
8076     0
52981    1
7624     0
Name: churn, Length: 73450, dtype: int64

In [39]:
X_test

tenure_months  monthly_usage_hours  has_multiple_devices  \
8543               7            22.580414                     0   
527                6            17.463274                     0   
39478              7            17.975821                     0   
64299              3            13.853962                     0   
11790              8            14.700862                     1   
...              ...                  ...                   ...   
64223              1             8.733033                     0   
61293              1            22.428005                     1   
63532              1            14.682813                     0   
46033             58            23.469554                     1   
80660              5            19.801282                     1   

       customer_support_calls  payment_failures  is_premium_plan  
8543                        4                 0                0  
527                         1                 0                0  
39478                       1                 0                1  
64299                       0                 0                0  
11790                       2                 0                0  
...                       ...               ...              ...  
64223                       2                 0                0  
61293                       0                 1                1  
63532                       1                 0                0  
46033                       0                 0                1  
80660                       1                 0                0  

[24484 rows x 6 columns]

In [41]:
y_test

8543     0
527      0
39478    0
64299    1
11790    0
        ..
64223    1
61293    1
63532    1
46033    0
80660    1
Name: churn, Length: 24484, dtype: int64

In [43]:
logistic=LogisticRegression(class_weight='balanced')
logistic.fit(X_train,y_train)

LogisticRegression(class_weight='balanced')

In [44]:
y_pred=logistic.predict(X_test)


In [46]:
print(accuracy_score(y_test,y_pred))

0.8397320699232151


In [49]:
print(confusion_matrix(y_test,y_pred))

[[ 9769  2444]
 [ 1480 10791]]


In [51]:
print(roc_auc_score(y_test,y_pred))

0.8396379003890037


In [53]:
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [55]:
p=dict(penalty=penalty,C=c_values,solver=solver)

In [57]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [59]:
grid=GridSearchCV(estimator=logistic,param_grid=p,scoring='accuracy')

In [ ]:
grid.fit(X_train,y_train)

In [62]:
y_pred1=grid.predict(X_test)

In [63]:
print(accuracy_score(y_test,y_pred1))

0.8403038719163536


In [64]:
print(confusion_matrix(y_test,y_pred1))

[[ 9771  2442]
 [ 1468 10803]]


In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
scaler=StandardScaler()

In [67]:
X_train1=scaler.fit_transform(X_train)

In [68]:
X_test1=scaler.transform(X_test)

In [69]:
logisticreg=LogisticRegression(class_weight='balanced')
logisticreg.fit(X_train1,y_train)

LogisticRegression(class_weight='balanced')

In [70]:
y_pred2=logisticreg.predict(X_test1)


In [71]:
print(accuracy_score(y_test,y_pred2))

0.8396912269237052


In [72]:
print(confusion_matrix(y_test,y_pred2))

[[ 9768  2445]
 [ 1480 10791]]


In [73]:
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [74]:
p=dict(penalty=penalty,C=c_values,solver=solver)

In [75]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [76]:
cv=StratifiedKFold()

In [77]:
grid1=GridSearchCV(estimator=logisticreg,param_grid=p,scoring='accuracy',cv=cv)

In [78]:
grid1.fit(X_train1,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver =

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(class_weight='balanced'),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [79]:
y_predict=grid1.predict(X_test1)

In [80]:
print(accuracy_score(y_test,y_predict))

0.8397320699232151


In [81]:
print(confusion_matrix(y_test,y_predict))

[[ 9768  2445]
 [ 1479 10792]]


In [82]:
from sklearn.metrics import roc_auc_score
print("ROC AUC Score:", roc_auc_score(y_test, grid.predict_proba(X_test1)[:, 1]))


ROC AUC Score: 0.7567480990966828


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [83]:
print(roc_auc_score(y_test,y_predict))

0.839637706882447


In [84]:
import pickle
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(grid,open('grid1.pkl','wb'))
pickle.dump(logisticreg,open('logisticreg.pkl','wb'))

In [102]:
### import pandas as pd

# Get input from the user
tenure_months = int(input("Enter tenure in months (e.g., 12): "))
monthly_usage_hours = float(input("Enter monthly usage in hours (e.g., 28.5): "))
has_multiple_devices = int(input("Has multiple devices? (1 = Yes, 0 = No): "))
customer_support_calls = int(input("Number of customer support calls (e.g., 2): "))
payment_failures = int(input("Number of payment failures (e.g., 0): "))
is_premium_plan = int(input("Is premium plan? (1 = Yes, 0 = No): "))

# Create DataFrame from inputs
input_data = pd.DataFrame([{
    "tenure_months": tenure_months,
    "monthly_usage_hours": monthly_usage_hours,
    "has_multiple_devices": has_multiple_devices,
    "customer_support_calls": customer_support_calls,
    "payment_failures": payment_failures,
    "is_premium_plan": is_premium_plan
}])

print("\n✅ User Input Data:")
print(input_data)
import joblib

# Load model
model = joblib.load("logisticreg.pkl")

# Predict
prediction = model.predict(input_df)
print("Prediction:", "Churn" if prediction[0] == 1 else "Not Churn")


Enter tenure in months (e.g., 12):  39
Enter monthly usage in hours (e.g., 28.5):  30.95
Has multiple devices? (1 = Yes, 0 = No):  0
Number of customer support calls (e.g., 2):  1
Number of payment failures (e.g., 0):  0
Is premium plan? (1 = Yes, 0 = No):  0



✅ User Input Data:
   tenure_months  monthly_usage_hours  has_multiple_devices  \
0             39                30.95                     0   

   customer_support_calls  payment_failures  is_premium_plan  
0                       1                 0                0  
Prediction: Not Churn


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [99]:
import joblib

# Load model
model = joblib.load("logisticreg.pkl")

# Predict
prediction = model.predict(input_df)
print("Prediction:", "Churn" if prediction[0] == 1 else "Not Churn")


Prediction: Not Churn


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
